### ISSUE TITLE
Things to improve 

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_webinar#2]
1. Make the logo 50% smaller
1. Make the body with the content narrower, this is a good example to follow: https://getbootstrap.com/docs/4.5/examples/checkout/
1. and please format all the elements in the boostrap way.
1. add a light grey line in the middle of the page, as from image included to the job posting 
1. remove the light grey border around the description 
1. on the form side, add a header same like `About the event` but write `Form`
1. the text `1H of open questions about the product and AWS over text` is the only text. and make it h3, and make the div holding he text narrow enough to wrap the text in 2 lines.
1. set the font to the same as here: https://consulting.0x4447.com/

**Comment by mcbianconi** [comment]
Made the changes, hope you like it
