### ISSUE TITLE
More fine tuning

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_webinar#6]
![Screen Shot 2020-07-11 at 4 27 14 PM](https://user-images.githubusercontent.com/411114/87226889-1ea79a80-c397-11ea-9684-b29c6d19a14f.png)

- [x] Move the time to the right to be in line with the right sdie of the page where the event is. and make it justify to the left, so it all starts from the header of the description. I hope this makes sense, if not let me know.
- [x] company size, make more jumps till the end as shown in the image
- [x] remove space in between company name and `TM`
- [x] add direct links to a external page, I will set later to the right ones.
- [x] make the non existing image take space and then fill the void, so the text dose not jump.
- [x] add a separate thank you page for each form, this is needed to track goals.

**Comment by mcbianconi** [comment]
Pushed to branch
