### ISSUE TITLE
New data structure

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_webinar#7]
@mcbianconi I did change how the data structure is done to simplify things :) Before we did pull 2 files from S3, now we need to just pull one, this one: `event.json` Indie you will see this structure:

```
{
	"title": "Learn how to setup our open OpenVPN solution",
	"summary": "0x4447 Webinar - OpenVPN Solution Setup",
	"description": "Nice description about the event",
	"image": "dynamodn.jpg",
	"meeting_id": "12323",
	"time": {
		"start": "2020-08-04T08:58:32+02:00",
		"end": "2020-08-04T09:58:32+02:00"
	}
}
```

You care about the: `title`, `description`, `image` and `time.start`

**Comment by mcbianconi** [comment]
Change done
