### ISSUE TITLE
Link to Image

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_webinar#8]
I made a bucket where I put all the assets, so please link the images with the right LINK: `https://s3.amazonaws.com/webinars.0x4447.com.db.assets/openvpn.png`

**Comment by mcbianconi** [comment]
Alright!

Gonna do it today at night and will notify you when its done!
We got a security breach where I work, thats why I could not work that much
in our project.

Hope you understand!
Thank you!

Em sex., 17 de jul. de 2020 às 05:21, David Gatti <notifications@github.com>
escreveu:

**Comment by davidgatti** [comment]
O no :( finger cross all will be OK.

**Comment by mcbianconi** [comment]
Done
