### ISSUE TITLE
A set of new buttons

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_webinar#9]
![Screen Shot 2020-07-18 at 12 00 42 PM](https://user-images.githubusercontent.com/411114/87850170-72156d80-c8ee-11ea-8549-cb10f93839b8.png)

We need to have a row of buttons that in the back ground needs to be checkmarks, that people can select to mark which product they would like to resell, and the validation needs to be a minimum of one.

Also this list needs to come from an JSON Array file that can be edited to add more in the future, here is the strucutre of one object in the array:

```
{
    "name": "OpenVPN,
    "id": "23123123"
}
```

You need to save in the in S3, the array with the whole object.

**Comment by mcbianconi** [comment]
The product list is in the `components/helpers/reseller.js` file to be easily modified.
